---
- name: setup lamp stack
  hosts: web
  become: yes
  tasks:
    - name: stop nginx if running
      service:
        name: nginx
        state: stopped
        enabled: no


    - name: install apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: install mysql
      apt:
        name: mysql-server
        state: present

    - name: install php
      apt:
        name: php
        state: present

    - name: start and enable apache 
      service:
        name: apache2
        state: started
        enabled: yes

    - name: start and enable mysql
      service:
        name: mysql
        state: started
        enabled: yes

    - name: deploy sample php info page
      copy:
        dest: /var/www/html/index.php
        content: "<?php phpinfo(); ?>"
    


